angular/ngcc-validation

angular-reduxstore-ngcc/package-lock.json
angular-reduxstore-ngcc/package.json

This package was failing because of a transitive dependency on redux.
See https://github.com/angular-redux/platform/issues/90#issuecomment-509832610.
@mgechev  - Will this PR get blasted by renovate?
Fixes https://github.com/mgechev/ngcc-validation/issues/58

Fix redux dependency for angular-redux/store

---

swimlanengx-datatable-ngcc/src/app/app.module.ts

Using ng `8.2.0-rc.0`, `ngx-datatable` is breaking in one of our Ivy apps with:
```
ERROR in node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts:1:22 - error TS-996002: Appears in the NgModule.imports of AdminModule, but could not be resolved to an NgModule class
1 export declare class NgxDatatableModule {
```
This PR should reproduce the build failure.

feat: break ngx-datable by using NxDatatableModule

---

renovate.json

`config:base` extends a number of presents https://renovatebot.com/docs/presets-config/ which are not needed for this use case.
Hence, use renovate defaults and just extend from `schedule:nonOfficeHours`

ci: fine tune renovate configuration

---

renovate.json

This will result in a single "master issue" being created in the repo that lets you view all upcoming and open PRs from Renovate and also to override any schedules to force open updates that would otherwise have to wait.

ci: enable renovate master issue

---

renovate.json

We moved to yarn which should be faster let’s try to enable digest updates again so that we Angular snapshots are updated automatically.
If we see that we don’t get renovate updates we should revert this commit.

ci: enable npm digest

---

README.md

- Replace npm with yarn 
- Remove redundant steps since now we have a monorepo, where deps and builds target are inherited

docs: update readme with new instructions

---

infra/passing.json
projects/devextreme-angular-ngcc/tsconfig.app.json

This package would previously fail to compile as its dependency on
`devextreme` > `jszip` was not configured properly, resulting in the
build error: `Module not found: Error: Can't resolve 'stream'`.
The documentation of `dexextreme` describes a fix for this issue, which
is to map the `jszip` import to its dist bundle.

Configure devextreme-angular properly

---

projects/carbonicons-angular-ngcc/src/app/app.module.ts

The `@carbon/icons-angular` package does not conform to APF and does not
have a source file at the supposed entry-point root of
`@carbon/icons-angular`. Therefore, the build error
`Module not found: Error: Can't resolve '@carbon/icons-angular'` would
occur.
This updates the import to an actual location, as documented by Carbon's
documentation. The package will still fail to compile, however, as ngcc
seems not to process the entry-point at all.

Update @carbon/icons-angular import

---

package.json
projects/nebulardate-fns-ngcc/tsconfig.app.json
projects/nebulardate-fns-ngcc/tsconfig.spec.json
yarn.lock

Fix a conflict between two packages that need different major versions of the `date-fns` package as peer dependencies.

Date fn versions

---

.circleci/config.yml

Currently, the CircleCI/Slack integration sends notifications on any failure. This can become noisy, because PRs often fail while people are working on them.
This commit changes the CircleCI config to only send Slack notifications for non-PR builds.

Send Slack notifications on non-PR buils only

---

projects/ng2-dragula-ngcc/src/polyfills.ts

Resolves https://github.com/angular/angular/issues/29703

fix ng2-dragula test application

---

.circleci/config.yml

Yarn (the service) randomly closes the connection for this package. The timeout helps us workaround the problem for https://github.com/angular/ngcc-validation/pull/452 and https://github.com/angular/ngcc-validation/pull/453.

Add yarn timeout

---

projects/uirouterangular-hybrid-ngcc/e2e/src/app.e2e-spec.ts
projects/uirouterangular-hybrid-ngcc/e2e/src/app.po.ts
projects/uirouterangular-hybrid-ngcc/src/app/child.component.html

Even once the compiler is fixed for this package, the e2e tests were
failing because they were boilerplate. They need special ngUpgrade
settings and were not testing the actual application.

ui-router/angular-hybrid: fix e2e tests

---

infra/failing-projects.json
projects/nebulartheme-ngcc/src/app/app.module.ts

Repro for https://github.com/angular/ngcc-validation/issues/529

demonstrate runtime error for @nebular/theme

---

infra/failing-projects.json
projects/covalentcore-ngcc/src/app/app.module.ts

Importing from the root entry-point does not seem to be
the recommended approach from looking at their docs.
The problem with doing this, is that the root package is
basically a concatenation of all the secondary entry-points
but uses the same typings files as the secondary entry-points.
This results in ngcc trying to write to the typings files twice.

tweak the covalent test app

---

projects/kendo-ui-ripple-ngcc/e2e/src/app.e2e-spec.ts
projects/kendo-ui-ripple-ngcc/e2e/src/app.po.ts

The previous e2e test for `@progress/kendo-angular-ripple` was flaky, because it relied on capturing the presence of the temporary ripple overlay element. Example failures:
- https://circleci.com/gh/angular/ngcc-validation/2360
- https://circleci.com/gh/angular/ngcc-validation/2368
This commit reduces the flakiness of the test by relying on detecting a different feature (the ripple target), which will not change until another element gains focus (so it is not susceptible to race conditions, unlike the ripple overlay).

test(@progress/kendo-angular-ripple): reduce flakiness in test

---

package.json
projects/swimlanengx-charts-ngcc/e2e/src/app.e2e-spec.ts
projects/swimlanengx-charts-ngcc/e2e/src/app.po.ts
yarn.lock

In addition to updating `@swimlane/ngx-charts` this PR also updates the e2e tests for the `swimlanengx-charts-ngcc` project to pass with the changes in v13 (in a way that
is hopefully less likely to break in the future) and fixes an issue with the `core-js-compat@3.4.6` dependency.
See individual commits for more details.
Closes #679.

build(deps): update dependency @swimlane/ngx-charts to v13

---

projects/kendo-ui-dialog-ngcc/src/polyfills.ts
projects/kendo-ui-notification-ngcc/e2e/src/app.po.ts
projects/kendo-ui-notification-ngcc/src/polyfills.ts

The Dialog and Editor components added localized messages in the latest versions. See build failures in #810.

fix: add polyfill to kendo-ui projects

---

renovate.json

Previously, all packages starting with `@angular` would be updated in a single PR. This made it difficult to investigate regressions that could have been caused by either the Angular framework or Angular material or the Angular CLI (e.g. in #839).
This commit configures Renovate to update framework, Material and CLI separately.

ci: configure renovate to update Angular framework, Material and CLI separately

---

renovate.json

Ensure other material packages, such as `@angular/material-experimental` and `@angular/material-moment-adapter` are part of the `angular-components` update group in Renovate config.

ci: fix patterns for `angular-components` Renovate group

---

infra/build-project.js

Sometimes, tests for a package fail due to random flakes. To reduce the failures due to these flakes, this commit attempts to run failed jobs commands a second time.
Example flakes:
- https://circleci.com/gh/angular/ngcc-validation/3979
- https://circleci.com/gh/angular/ngcc-validation/3980

ci: retry failed jobs to reduce flakes

---

infra/failing-projects.json

@covalent/core v3 no longer fails to be processed by ngcc.
Fixed by #1045.

Remove `covalentcore-ngcc` from failing projects

---

package.json
yarn.lock

Support for TypeScript version <3.8 was dropped from Angular in angular/angular#36329. In order to allow updates to the latest Angular framework, this commit updates TypeScript to the latest 3.8.x version.

build: upgrade TypeScript to 3.8.3

---

projects/bugsnagplugin-angular-ngcc/src/app/app.module.ts

Bugsnag complains that the API key should be a string of 32 hexadecimal characters. Using a dummy 32 char long string to keep Bugsnag from complaining.

fix(bugsnagplugin-angular-ngcc): use a 32 chars hex string as API key

---

ngcc.config.standalone.js
package.json
renovate.json
yarn.lock

The issue that caused ngcc processing to fail on UMD bundles has been fixed in this version of `@angular/flex-layout`, so we can remove the ngcc config for ignoring the UMD bundles.

build(deps): update @angular/flex-layout to v9.0.0-beta.30

---

angular.json
infra/build.ts
infra/failing-projects.json
infra/ng-build-projects.json
package.json
projects/angularplatform-server-ngcc/custom-test.js
projects/angularplatform-server-ngcc/server.ts
projects/angularplatform-server-ngcc/src/app/app.module.ts
projects/angularplatform-server-ngcc/src/app/app.server.module.ts
projects/angularplatform-server-ngcc/src/main.server.ts
projects/angularplatform-server-ngcc/src/main.ts
projects/angularplatform-server-ngcc/tsconfig.app.json
projects/angularplatform-server-ngcc/tsconfig.server.json
tsconfig.json
yarn.lock

Previously, the project used to verify the `@angular/platform-server` package's compatibility with ngcc was importing `@angular/platform-server` into the app (which is not what would happen in an actual app).
This commit changes the project to look more like a real-world app. It also changes the tests to make sure they better exercises the SSR functionality.

refactor: change `@angular/platform-server` project/test to be more realistic

---

infra/failing-projects.json

It seems that the latest version of `@alfresco/*` packages can be successfully compiled by ngcc.
This PR removes `alfrescoadf-core-ngcc` from the list of failing projects.

build: remove `alfrescoadf-core-ngcc` from failing projects

---

.circleci/config.yml
infra/failing-projects.json

`@angular-devkit/build-angular` v0.1102.0-next.1 will require a Node.js version >= 12.13.0 ([package.json][1]). Previously, the docker image used on CI came with Node.js v12.9, which was causing Node.js engine incompatibility failures ([example failure][2]).
This commit updates the docker image used on CI to one that uses Node.js v14.15.4 (the latest LTS atm).
It also adds a step to log the versions of Node.js, npm and yarn for easier debugging.
[1]: https://github.com/angular/angular-devkit-build-angular-builds/blob/6d8121721f838668a7e1aa13ab9c01ae2b63e4e4/package.json#L128
[2]: https://circleci.com/gh/angular/ngcc-validation/24554

ci: upgrade Node.js to v14.15.4

---

ngcc.config.standalone.js

See individual commits for details:
- [**build: remove `@alfresco/adf-core` from the list of ignored packages**](https://github.com/angular/ngcc-validation/pull/2550/commits/77fcf8b6e516afa8c19bc68ab4f4264ab08fc64d)
- [**build: stop overriding the `main` field of `@carbon/icons-angular`**](https://github.com/angular/ngcc-validation/pull/2550/commits/a7437e65c857edd57285b3352d76c8cf07727c0a)

build: remove ignored/overriden packages from the ngcc standalone config

---

renovate.json

The way Renovate works when automerging is enabled causes many CI re-runs. (I.e. all open PRs have to be rebased once another PR has been merged.)
This commit limits the number of concurrent PRs to 2 to minimize the number of redundant CI re-runs. We are not setting the limit to 1, because that would mean that one failing PR would block all other updates until that PR is closed.
See also:
- [Docs on prConcurrentLimit][1].
- [Discussion][2] with more details on the problem and the available solutions.
[1]: https://docs.renovatebot.com/configuration-options/#prconcurrentlimit
[2]: https://github.com/renovatebot/renovate/discussions/8982

ci(renovate): limit PR concurrency to 2

---

renovate.json

Previously, Renovate was configured to use the [nonOfficeHours][1] schedule preset, which allows it to do work between 10pm and 5am on weekdays (and around the clock on weekends). Given recent changes to limit branch/PR concurrency to 2 (see [here][2] and #2650 for context), this does not allow Renovate to work through its backlog of updates fast enough.
This PR widens Renovate's "working" hours on weekdays from 7h to 13h (between 6pm and 7am) to allow it more time to catch up with its backlog, despite the limited concurrency.
[1]: https://docs.renovatebot.com/presets-schedule/#schedulenonofficehours
[2]: https://github.com/renovatebot/renovate/discussions/8982

ci(renovate): update schedule to increase Renovate "working" hours

---

renovate.json

This commit configures Renovate to run on the `latest` branch (in addition to `master`). The `latest` branch is for testing libraries against the `@latest` (i.e. stable) versions of Angular/CLI/Components.
The config is also updated to allow 3 concurrent PRs, since now Renovate will need to create PRs for 2 branches.

ci: configure Renovate to run on both `master` and the `latest` branches

---

package.json
yarn.lock

This reverts commit 764b7a7d6e3bf195c87c371c62bcb769283f3c8b.
`@alfresco/adf-core` v4.4.0 still relies on `SELECT_ITEM_HEIGHT_EM` exported by older versions of `@angular/material/select`. Since angular/components@99391e79391d20c6ef2f95a3ea4fd6901dcb631d, this constant is no longer exported by `@angular/material/select`. Therefore, we need to wait for a version of `@alfresco/adf-core` that is compatible with `@angular/material` v12.
Therefore, PR #3773 should have failed on CI and not be merged into master. For some reason, the [`setup` CI job][1] for that PR failed, but the PR was automatically merged by Renovate, subsequently causing [CI to fail][2] for master.
This PR reverts the change to fix master.
[1]: https://circleci.com/gh/angular/ngcc-validation/47844
[2]: …

Revert "build(deps): update alfresco"

---

.circleci/config.yml

Previously, the `setup` job did not include any tests (that could potentially fail). Since recently, however, in contains the `check-ngcc-packages` check, which can potentially fail and require user action to be resolved.
This commit updates the `setup` job to send a notification on Slack (as the other CI jobs do) whenever it fails, letting the team know that the might need to manually fix the issue (for example, for a PR to be merged).

ci: notify on Slack when `check-ngcc-packages` fails

---

.circleci/config.yml

Previously, the `setup` job did not include any tests (that could potentially fail). Since recently, however, in contains the `check ngcc-packages` check, which can potentially fail and require user action to be resolved.
This commit updates the `setup` job to send a notification on Slack (as the other CI jobs do) whenever it fails, letting the team know that the might need to manually fix the issue (for example, for a PR to be merged).

[latest] ci: notify on Slack when `check-ngcc-packages` fails

---

renovate.json

The renovate config is currently invalid JSON after the recent
changes in: db504daa46c4c7b0b9562648d2681e296cf99af5.

build: fix renovate config after recent changes

---

infra/is-ngcc-necessary.ts

In order to identify direct dependencies that no longer need `ngcc` processing, the `check-ngcc-packages` npm script checks all packages and lists the ones that no longer need `ngcc` processing (unless they are included in list of known packages).
To give a better picture of the progress on switching packages to Ivy, the script will now also log how many packages still need `ngcc` processing.

ci: log number of dependencies that still need `ngcc` processing

---

.circleci/config.yml
projects/kendo-ui-charts-ngcc/e2e/src/app.e2e-spec.ts

Older versions of Chrome are no longer available, leading to CI failures ([example failure][1]).
[1]: https://circleci.com/gh/angular/ngcc-validation/106912

ci: update Chrome/ChromeDriver versions to latest
